name: Deploy HTML file to S3

on: ["push", "workflow_dispatch"]

jobs: 
    deploy-me:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code from the repo
              uses: actions/checkout@v4
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}
                aws-region: ${{ vars.AWS_REGION }}
