name: If-Demo
on:
    push:
        branches:
            - main
jobs:
    demo:
        runs-on: ubuntu-latest
        steps: 
            - name: Run this step if branch is main
              if: github.ref == 'refs/heads/main'
              run: echo "Run for MAIN branch"

            - name: Run this step
              run: echo "This step is running"
            