name: Inputs Demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Choose an environment to deploy
        required: true
        default: dev
        options:
            - dev
            - test
            - production
      artifact_tag:
        description: Choose a tag for the deployment
        required: true
        default: latest


jobs:
    inputs-demo:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the App
              run: echo "Deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}"